webapp/apps/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.list_orders, name='list_orders'),
    path('adicionar/', views.add_order, name='add_order'),
    path('editar/<int:id_order>/', views.edit_order, name='edit_order'),
    path('excluir/<int:id_order>/', views.delete_order, name='delete_order'),
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace = 'core')),
    path('categorias/', include('categories.urls', namespace='categories')),
    path('redessociais/', include('socialnetworks.urls', namespace='socialnetworks')),
    path('produtos/', include('products.urls', namespace='products')),
    path('clientes/', include('clients.urls', namespace='clients')),
    path('pedidos/', include('orders.urls', namespace='orders')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/apps/orders/models.py
from django.db import models

from products.models import Product
from clients.models import Client

# Create your models here.
class Order(models.Model):
    quantity = models.IntegerField('Quantidade',null=True, blank=True)
    price = models.FloatField('Preco',null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        ordering =['id']

    def __str__(self):
        return self.product.name

webapp/apps/orders/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ()

webapp/apps/orders/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import OrderForm
from .models import Order

# Create your views here.
def add_order(request):
    template_name = 'orders/add_order.html'
    context = {}
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('orders:list_orders')
    form = OrderForm()
    context['form'] = form
    return render(request, template_name, context)

def list_orders(request):
    template_name = 'orders/list_orders.html'
    orders = Order.objects.filter()
    context = {
        'orders': orders
    }
    return render(request, template_name, context)

def edit_order(request, id_order):
    template_name = 'orders/add_order.html'
    context ={}
    order = get_object_or_404(Order, id=id_order)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('orders:list_orders')
    form = OrderForm(instance=order)
    context['form'] = form
    return render(request, template_name, context)

def delete_order(request, id_order):
    order = Order.objects.get(id=id_order)
    order.delete()
    return redirect('orders:list_orders')

webapp/templates/orders/add_order.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Pedido - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Pedido</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.quantity.id_for_label }}">Quantidade</label>
                   {{ form.quantity|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.price.id_for_label }}">Preco</label>
                    {{ form.price|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.client.id_for_label }}">Cliente</label>
                    {{ form.client|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.product.id_for_label }}">Produto</label>
                    {{ form.product|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

webapp/templates/orders/list_orders.html
{% extends 'base.html' %}

{% block title %}

Lista de Pedidos - {{ block.super }}

{% endblock title %}

{% block body %}

<div class="container">
    <br />
    <h5><b>Lista de Pedidos</b></h5>
    <div class="row">
        <div class="col-md-12">
            <br />
            <a href="{% url 'orders:add_order' %}">Cadastro de novo pedido</a>
            <br />
            <br />
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Quantidade</th>
                        <th scope="col">Preco</th>
                        <th scope="col">Cliente</th>
                        <th scope="col">Produto</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr>
                        <th scope="row">{{ order.id }}</th>
                        <td>{{ order.quantity }}</td>
                        <td>{{ order.price }}</td>
                        <td>{{ order.client }}</td>
                        <td>{{ order.product }}</td>
                        <td>
                            <a href="{% url 'orders:edit_order' order.id %}" class="btn btn-primary btn-sm">Editar</a>
                            <a href="{% url 'orders:delete_order' order.id %}"
                                class="btn btn-danger btn-sm ">Excluir</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock body %}